server:
  port: 8080
  servlet:
    context-path: "/${spring.application.api-version}"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/car_shop_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true