# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: 'postgres:14.13'
    container_name: 'java-postgres'
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car_shop_db
    ports:
      - "5440:5432"